/// Flutter icons ProfileIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProfileIcon
///      fonts:
///       - asset: fonts/ProfileIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProfileIcon {
  ProfileIcon._();

  static const _kFontFam = 'ProfileIcon';
  static const String? _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
