/// Flutter icons TruckIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TruckIcon
///      fonts:
///       - asset: fonts/TruckIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TruckIcon {
  TruckIcon._();

  static const _kFontFam = 'TruckIcon';
  static const String? _kFontPkg = null;

  static const IconData truck = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
