/// Flutter icons EyeOff
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EyeOff
///      fonts:
///       - asset: fonts/EyeOff.ttf
///
///
///
import 'package:flutter/widgets.dart';

class EyeOff {
  EyeOff._();

  static const _kFontFam = 'EyeOff';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData eye_off =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
