/// Flutter icons GiftIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GiftIcon
///      fonts:
///       - asset: fonts/GiftIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GiftIcon {
  GiftIcon._();

  static const _kFontFam = 'GiftIcon';
  static const String? _kFontPkg = null;

  static const IconData gift = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
