/// Flutter icons LocationIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LocationIcon
///      fonts:
///       - asset: fonts/LocationIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class LocationIcon {
  LocationIcon._();

  static const _kFontFam = 'LocationIcon';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData map_pin =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
