/// Flutter icons LogOutIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LogOutIcon
///      fonts:
///       - asset: fonts/LogOutIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class LogOutIcon {
  LogOutIcon._();

  static const _kFontFam = 'LogOutIcon';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData log_out =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
