// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCz-9nkXY0mpp2jjtK3g_DOe_YAWOX6wE',
    appId: '1:790774396706:web:b16cab0e5f3dbf3526d77b',
    messagingSenderId: '790774396706',
    projectId: 'delmer-9d425',
    authDomain: 'delmer-9d425.firebaseapp.com',
    databaseURL: 'https://delmer-9d425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delmer-9d425.appspot.com',
    measurementId: 'G-FDPW7N80MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVOfIXJm88Ti6ZG8zw5sNkhJRkrLdR0ak',
    appId: '1:790774396706:android:cc7a31e7cc8a1c1b26d77b',
    messagingSenderId: '790774396706',
    projectId: 'delmer-9d425',
    databaseURL: 'https://delmer-9d425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delmer-9d425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjQTurMfwA9wf_bCKD9wfLMJdzWDk-3pk',
    appId: '1:790774396706:ios:d2dd1f70217e7b4d26d77b',
    messagingSenderId: '790774396706',
    projectId: 'delmer-9d425',
    databaseURL: 'https://delmer-9d425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delmer-9d425.appspot.com',
    iosClientId: '790774396706-hmmjpqr66q63budbqjihahqbv44630o5.apps.googleusercontent.com',
    iosBundleId: 'uz.felix.delmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjQTurMfwA9wf_bCKD9wfLMJdzWDk-3pk',
    appId: '1:790774396706:ios:fa99dd315590218526d77b',
    messagingSenderId: '790774396706',
    projectId: 'delmer-9d425',
    databaseURL: 'https://delmer-9d425-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delmer-9d425.appspot.com',
    iosClientId: '790774396706-nofbpufodtm95ticna3qprkmq7ds1399.apps.googleusercontent.com',
    iosBundleId: 'uz.felix.delmer.RunnerTests',
  );
}
